name = "orange-meets"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"
account_id = "d71904723e6d118e50165cf7145c4790"
main = "./build/index.js"

[site]
  bucket = "./public"

[[build.upload.rules]]
  type = "ESModule"
  globs = ["**/*.js"]

[vars]
CALLS_APP_ID = "bf6b358f12766c81f5cfaf47f435c5fe"

[durable_objects]
 bindings = [
  { name = "rooms", class_name = "ChatRoom" }
]

# Indicate that you want the ChatRoom class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]

# The necessary secrets are:
# - CALLS_APP_SECRET
# To add secret, run `echo <VALUE> | wrangler secret put <NAME>`
